package com.bupt.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bupt.greendao.TableNews;
import com.bupt.greendao.TableAnimaJokes;
import com.bupt.greendao.TablePicJokes;
import com.bupt.greendao.TableTextJokes;
import com.bupt.greendao.TableBeautyPics;

import com.bupt.greendao.TableNewsDao;
import com.bupt.greendao.TableAnimaJokesDao;
import com.bupt.greendao.TablePicJokesDao;
import com.bupt.greendao.TableTextJokesDao;
import com.bupt.greendao.TableBeautyPicsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableNewsDaoConfig;
    private final DaoConfig tableAnimaJokesDaoConfig;
    private final DaoConfig tablePicJokesDaoConfig;
    private final DaoConfig tableTextJokesDaoConfig;
    private final DaoConfig tableBeautyPicsDaoConfig;

    private final TableNewsDao tableNewsDao;
    private final TableAnimaJokesDao tableAnimaJokesDao;
    private final TablePicJokesDao tablePicJokesDao;
    private final TableTextJokesDao tableTextJokesDao;
    private final TableBeautyPicsDao tableBeautyPicsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableNewsDaoConfig = daoConfigMap.get(TableNewsDao.class).clone();
        tableNewsDaoConfig.initIdentityScope(type);

        tableAnimaJokesDaoConfig = daoConfigMap.get(TableAnimaJokesDao.class).clone();
        tableAnimaJokesDaoConfig.initIdentityScope(type);

        tablePicJokesDaoConfig = daoConfigMap.get(TablePicJokesDao.class).clone();
        tablePicJokesDaoConfig.initIdentityScope(type);

        tableTextJokesDaoConfig = daoConfigMap.get(TableTextJokesDao.class).clone();
        tableTextJokesDaoConfig.initIdentityScope(type);

        tableBeautyPicsDaoConfig = daoConfigMap.get(TableBeautyPicsDao.class).clone();
        tableBeautyPicsDaoConfig.initIdentityScope(type);

        tableNewsDao = new TableNewsDao(tableNewsDaoConfig, this);
        tableAnimaJokesDao = new TableAnimaJokesDao(tableAnimaJokesDaoConfig, this);
        tablePicJokesDao = new TablePicJokesDao(tablePicJokesDaoConfig, this);
        tableTextJokesDao = new TableTextJokesDao(tableTextJokesDaoConfig, this);
        tableBeautyPicsDao = new TableBeautyPicsDao(tableBeautyPicsDaoConfig, this);

        registerDao(TableNews.class, tableNewsDao);
        registerDao(TableAnimaJokes.class, tableAnimaJokesDao);
        registerDao(TablePicJokes.class, tablePicJokesDao);
        registerDao(TableTextJokes.class, tableTextJokesDao);
        registerDao(TableBeautyPics.class, tableBeautyPicsDao);
    }
    
    public void clear() {
        tableNewsDaoConfig.getIdentityScope().clear();
        tableAnimaJokesDaoConfig.getIdentityScope().clear();
        tablePicJokesDaoConfig.getIdentityScope().clear();
        tableTextJokesDaoConfig.getIdentityScope().clear();
        tableBeautyPicsDaoConfig.getIdentityScope().clear();
    }

    public TableNewsDao getTableNewsDao() {
        return tableNewsDao;
    }

    public TableAnimaJokesDao getTableAnimaJokesDao() {
        return tableAnimaJokesDao;
    }

    public TablePicJokesDao getTablePicJokesDao() {
        return tablePicJokesDao;
    }

    public TableTextJokesDao getTableTextJokesDao() {
        return tableTextJokesDao;
    }

    public TableBeautyPicsDao getTableBeautyPicsDao() {
        return tableBeautyPicsDao;
    }

}
